### PR TITLE
Bug 1877261: UPSTREAM: 673: Feature/support disk waiting during mount

### PR DESCRIPTION
**Pull request by RomanBednar**
This is a cherry-pick of: https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/pull/673

Required for OCP 4.13: https://issues.redhat.com/browse/OCPBUGSM-17094

### CODE REVIEW

**Comment by RomanBednar** [comment]
/hold

Need to troubleshoot CI.

**Comment by jsafrane** [comment]
/retitle Bug 1877261: UPSTREAM: 673: Feature/support disk waiting during mount

**Comment by jsafrane** [comment]
> Message: code: 400, Total Zone count exceed the maximum

/retest

**Comment by jsafrane** [comment]
/lgtm
/approve
I went through all CI errors in this PR, they were caused either by the infrastructure or by OLM pods not ready, which is unrelated to this PR.

**Pull request merged**
