### PR TITLE
Bug 2047190: Rebase to v1.1.6

### PR DESCRIPTION
**Pull request by jsafrane**
Diff to upstream v1.1.6: https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/compare/v1.1.6...jsafrane:rebase-v1.1.6

I had to fix the build itself via `<carry>` / `<drop>` patches:
* Remove jindofs-fuse-3.7.3-20211207.tar.gz  - our dist-git does not like large files (and it's not used anyway).
* Comment out `cp build/oss/jindofs-fuse build/ack/jindofs-fuse` - the file does not exist in the repository (it's a different one than the previous one). It's in a CSI driver that we don't ship.
* Run `go mod vendor` to get missing `gogo/protobuf/types/*`

@openshift/storage

### CODE REVIEW

**Comment by jsafrane** [comment]
/hold
for QA to approve

**Review by bertinatto — COMMENTED** [review]
/lgtm
@jsafrane, can you update the description with the right diff link? 
https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/compare/v1.1.6...jsafrane:rebase-v1.1.6

**Comment by jsafrane** [comment]
Link updated

**Comment by duanwei33** [comment]
After testing with the pre-merged nightly with the new version CSI Driver, the result looks good. Removing the hold label.

/remove hold

**Comment by jsafrane** [comment]
/hold cancel
?

**Pull request merged**
