### PR TITLE
OCPBUGS-6349: UPSTREAM: 730: Fix CVE 2022 41717

### PR DESCRIPTION
**Pull request by jsafrane**
Upstream PR: https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/pull/730

This was quite manual cherry-pick, mostly doing `go get -u golang.org/x/net@0.4.0` manually.

### CODE REVIEW

**Review by bertinatto — COMMENTED** [review]
With Go 1.19 I get a different `go.sum` when I run `go mod tidy`, can you take a look?

**Comment by bertinatto** [comment]
/retitle OCPBUGS-6349: UPSTREAM: 730: Fix CVE 2022 41717

**Comment by jsafrane** [comment]
New golang.org/x/sys/unix/ requires go 1.16, while go.mod specifies 1.12

**Comment by jsafrane** [comment]
We may need to wait for https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/pull/733

**Comment by jsafrane** [comment]
Added https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/pull/734

**Pull request merged**
